DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS posts (
  id      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  content TEXT,
  author  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS comments (
  id      INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  content TEXT,
  author  VARCHAR(255),
  post_id INTEGER,
  FOREIGN KEY(post_id) REFERENCES posts(id)
);